- name: ping the server
  hosts: web
  #hosts: frontend
  tasks:
   - name: ping the web server
     ansible.builtin.ping:
   
 #Playbook is a list of tasks that can be exceuted against any server as apart of CM.