- name: variable preferences
  hosts: local
  connection: local
  vars:
    NAME: "Ansible from Play level"
  vars_files:
   - course.yaml
  vars_prompt:
    - name: username 
      prompt: Please enter username
      private: false
  tasks:
  - name: Task level variable
    vars:
     Course: "Ansible from task level"
    ansible.builtin.debug:   
      msg: "Course is: {{ Course}}"

    