- name : Filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, mysql

  tagsList: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]  
  tasks:
    - name: greeting
      ansible.builtin.debug:
       msg: " Hi ,{{ Greeting | default ('Good Morning') }}"  # deafult is the filter, when variable is undefined or empty 

    - name: convert string to lists
      ansible.builtin.debug:
        msg: " {{ topics | split (' ,')}}"   

    - name: convert lists to map
      ansible.builtin.debug:
       msg: "{{ tagsList | dic2items }}"    