- name: Nginx install
  hosts: local
  become: true
  tasks:
  - name: Install Nginx
    ansible.builtin.package:
    name: Nginx
    state: present

  - name: Start Nginx
    ansible.builtin.services:
    name: nginx
    state: started
    enable: yes 
     