- name: play level variables
  hosts: local
  connection: local  #By  giving connection as local you cannoot enter user name and password.
  var:
    Course: "DevOps"
    Training hours: "120"
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg : "Course is :{{ Course }} , Training hours is :{{ Training Hours }}" #Double flower braces inside the variable name to get the variable

      