- name: tasks level variables
  hosts: local
  connection: local
  vars:
    Course: "DevOps" 
    Traininghours: "120"
  tasks:
  - name: print the variables
    vars:
      Course: "Ansible"
    ansible.builtin.debug:
      msg: "Course is: {{ Course }} , Traininghours is: {{ TrainingHours }}"
# Inheritence : globally getting the vars,overide the vars.
 